name: Nord Layer Homework Pipeline
run-name: ${{ github.actor }} triggered build ğŸš€
on: [push]
jobs:
  - Setup:
    runs-on: ubuntu-latest
    concurrency:
      group: setup
      cancel-in-progress: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Lint
        run: |
          npm install
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
  - Lint:
    runs-on: ubuntu-latest
    concurrency:
      group: check
      cancel-in-progress: true
    steps:
      - name: Lint
        run: npm run lint
  - Test:
    runs-on: ubuntu-latest
    concurrency:
      group: check
      cancel-in-progress: true
    steps:
      - name: Test
        run: npm run test
